
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Amman&useUnicode=true&characterEncoding=UTF-8
    username: playfire
    password: .vKv6&rE~Z
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false